language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
install:
  - pip3 install -r requirements.txt
script:
  - scrapy bench
  - cd src
  - scrapy crawl collector --set CLOSESPIDER_ITEMCOUNT=1 --loglevel WARNING
