BOT_NAME = 'harvest'
SPIDER_MODULES = ['harvest.spiders']
NEWSPIDER_MODULE = 'harvest.spiders'

DOWNLOAD_DELAY = 3
CONCURRENT_REQUESTS = 2
COOKIES_ENABLED = False

SCHEDULER_DIR = 'cache'
FEED_URI = 'crawled/data.csv'
FEED_FORMAT = 'csv'

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 60
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
AUTOTHROTTLE_DEBUG = False
